app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from settings.settings import Config

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)

from apps.tasks import bp

app.register_blueprint(bp, url_prefix='/tasks')


if __name__ == "__main__":
    app.run(debug=True)

apps/tasks/__init__.py
from flask import Blueprint

bp = Blueprint('tasks', __name__)

from apps.tasks import views

apps/tasks/views.py
from flask import render_template, request, redirect, url_for

from app import db
from apps.tasks import bp

from apps.tasks.models import Todo


@bp.route('/', methods=['GET'])
def index():
    tasks = Todo.query.order_by(Todo.date_created).all()
    return render_template('index.html', tasks=tasks)


@bp.route("/create/", methods=['POST'])
def create():
    task_content = request.form['content']
    new_task = Todo(content=task_content)

    try:
        db.session.add(new_task)
        db.session.commit()
        return redirect(url_for('tasks.index'))
    except Exception as ex:
        print(ex)
        return 'There was an issue adding your task'

@bp.route('/delete/<int:id>')
def delete(id):
    task_to_delete = Todo.query.get_or_404(id)

    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect(url_for('tasks.index'))
    except:
        return 'There was a problem deleting that task'


@bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    task = Todo.query.get_or_404(id)

    if request.method == 'POST':
        task.content = request.form['content']

        try:
            db.session.commit()
            return redirect(url_for('tasks.index'))
        except:
            return 'There was an issue updating your task'

    else:
        return render_template('update.html', task=task)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock %}

{% block body %}
<div class="content">
    <h1 style="text-align: center">Task Master</h1>
    {% if tasks|length < 1 %}
    <h4 style="text-align: center">There are no tasks. Create one below!</h4>
    {% else %}
    <table>
        <tr>
            <th>Task</th>
            <th>Added</th>
            <th>Actions</th>
        </tr>
        {% for task in tasks %}
            <tr>
                <td>{{ task.content }}</td>
                <td>{{ task.date_created.date() }}</td>
                <td>
                    <a href={{ url_for('tasks.delete', id=task.id) }}>Delete</a>
                    <br>
                    <a href={{ url_for('tasks.update', id=task.id) }}>Update</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% endif %}

    <div class="form">
        <form action={{ url_for('tasks.create') }} method="POST">
            <input type="text" name="content" id="content">
            <input type="submit" value="Add Task">
        </form>
    </div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock %}

{% block body %}
<div class="content">
    <h1 style="text-align: center">Update Task</h1>

    <div class="form">
        <form action={{ url_for('tasks.update', id=task.id) }} method="POST">
            <input type="text" name="content" id="content" value="{{task.content}}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock %}